module Result {
  fun error (input : a) : Result(a, b) {
    `new Err(#{input})`
  }
}

component Main {
  fun test : Promise(Never, String) {
    sequence {
      Result.error("")

      "test"
    } catch {
      "test"
    }
  }

  fun render : Html {
    test()

    <div/>
  }
}
--------------------------------------------------------------------------------
const B = new(class extends _M {
  b(c) {
    return (new Err(c));
  }
});

class A extends _C {
  a() {
    return (async () => {
      let _ = null;

      try {
        let _0 = B.b(``);

        if (_0 instanceof Err) {
          throw _0._0
        };

        _0._0;

        _ = await `test`;
      } catch (_error) {
        if (!(_error instanceof DoError)) {
          _ = `test`
        }
      };

      return _;
    })();
  }

  render() {
    this.a();
    return _h("div", {});
  }
};

A.displayName = "Main";
